---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm dev-webserver sh -c "python manage.py wait_for_db && python manage.py collectstatic && python manage.py test apps"
      - name: Lint
        run: docker-compose run --rm dev-webserver sh -c "flake8 & yarn --modules-folder /node_modules eslint"
